const menu = [
  {
    id: 1,
    title: "Eggs Ben-appetit",
    category: "Breakfast",
    price: 1,
    img: "./foodmenuimages/eggsbenedict.jpg",
    desc: `Eggs Benedict is a dish with origins in the US, whose recipe has been exported to countries around the world.`,
  },
  {
    id: 2,
    title: "Sizzling Chicken Sweet Potato",
    category: "Lunch",
    price: 15.99,
    img: "./foodmenuimages/sizzlingchicken.jpg",
    desc: `This quick and easy spicy chicken can be used in a rice or grain bowl, a taco or lettuce wrap or with simple steamed greens or vegetables.`,
  },
  {
    id: 3,
    title: "Fish Feel'It",
    category: "Dinner",
    price: 13,
    img: "./foodmenuimages/fishfillet.jpg",
    desc: `Pat-dry the fish fillets then cut each fillet into 2 pieces lengthwise (since the fillet is uneven in thickness, this operation ensures uniform cooking).`,
  },
  {
    id: 4,
    title: "Super Cheesy Cakey-Cake",
    category: "Dessert",
    price: 17.99,
    img: "./foodmenuimages/cheesecake.jpg",
    desc: `Making cheesecake is easier than you think! Whip up one of these easy, homemade cheesecake recipes to impress your friends.`,
  },
  {
    id: 5,
    title: "Steak-ier Cobb Salad",
    category: "Lunch",
    price: 13.99,
    img: "./foodmenuimages/steak.jpg",
    desc: `In a large bowl, combine the romaine lettuce, Belgian endive, red onion, baby arugula and cherry tomatoes, and half of the cheese.`,
  },
  {
    id: 6,
    title: "All-Time High-Time Breakfast Burrito",
    category: "Breakfast",
    price: 7.99,
    img: "./foodmenuimages/breakfastburrito.jpg",
    desc: `A breakfast burrito is traditionally filled with ingredients typical of an American breakfast like eggs, hash browns and sausage or bacon to start.`,
  },
  {
    id: 7,
    title: "Apple With A Hint Of Vinegar",
    category: "Drink",
    price: 1,
    img: "./foodmenuimages/appledrink.jpg",
    desc: `Apple cider is, essentially, an unfiltered apple juice that tends to have a stronger flavor, so it's perfect for mixed drinks.`,
  },
  {
    id: 8,
    title: "Quesadillas All-Nighter",
    category: "Dinner",
    price: 5.99,
    img: "./foodmenuimages/quesa.jpg",
    desc: `In its most basic form, a quesadilla is simply a grilled tortilla with melted cheese inside.`,
  },
  {
    id: 9,
    title: "Pancake Delight",
    category: "Breakfast",
    price: 1.99,
    img: "./foodmenuimages/pancakes.jpg",
    desc: `This is the best fluffy pancakes recipe according to my family. They are quick and easy to prepare.`,
  },
  {
    id: 10,
    title: "Stir O' Pry",
    category: "Dinner",
    price: 20,
    img: "./foodmenuimages/stirfry.jpg",
    desc: `These hearty versions of stir-fry feature rich ingredients, like shrimp and hoisin sauce, that make a quick weeknight meal feel gourmet.`,
  },
  {
    id: 11,
    title: "Ala Mangga Float",
    category: "Dessert",
    price: 40,
    img: "./foodmenuimages/mangofloat.jpg",
    desc: `Mango float is a popular dessert in the Philippines. It also goes by the names: Mango Royale or Crema de Mangga.`,
  },
  {
    id: 12,
    title: "Cinnamon Roll-ing In The Deep",
    category: "Breakfast",
    price: 2.99,
    img: "./foodmenuimages/cinnamon.jpg",
    desc: `Cinnabons Cinnamon Rolls – a cinnabon copycat recipe, about the closest you'll get to the real thing. Super easy to make.`,
  },
  {
    id: 13,
    title: "Mojo Jito",
    category: "Drink",
    price: 9,
    img: "./foodmenuimages/mojito.jpg",
    desc: `Place ice in beverage shaker then add in the rum, 8 broken up mint sprigs, lime juice and sugar.`,
  },
  {
    id: 14,
    title: "Lamb-Orghini Special",
    category: "Lunch",
    price: 13.99,
    img: "./foodmenuimages/lamb.jpg",
    desc: `Lamb's rich in protein & other essential vitamins and minerals. We've rounded up our favourite lamb meal prep meals for when you're on-the-go.`,
  },
  {
    id: 15,
    title: "The Churros",
    category: "Dessert",
    price: 5.99,
    img: "./foodmenuimages/churros.jpg",
    desc: `In my opinion Churros are one of the worlds best desserts – when made fresh from scratch of course.`,
  },
];

export default menu;
